### ISSUE TITLE
Improve compatibility with the Better PathOfExile Trading extension

### ISSUE THREAD

**Issue by Riboe** [RenuzitV/Trade-Aggregator#2]
[Better PathOfExile Trading](https://chromewebstore.google.com/detail/better-pathofexile-tradin/fhlinfpmdlijegjlpgedcmglkakaghnk) is a very popular extension, which also adds useful features to the official PoE trade website.  
Unfortunately, it also uses the right hand side of the site for its UI.

This means that the UI for this script and for the extension overlaps, making it difficult to use this script.

I have only just taken a very quick look at a potential solution, but it's very simple and seems to work well.

The extension adds the class `.bt-body` to the `body` element. This means you can include CSS rules that are only in effect when the extension is installed.

The extension UI has a fixed with of 400px, so simply moving the aggregator UI fixes the overlap issue.

```css
.bt-body > #aggregator {
    right: 400px !important;
}
```

However, users can also collapse the extension UI. When doing so, another class is added to the HTML `body` element: `.bt-is-collapsed`.  
Some simple CSS can then be applied to properly position the aggregator overlay in this case:

```css
.bt-is-collapsed > #aggregator {
    right: 0 !important;
}
```

These two rules causes the aggregator UI to be positioned properly and not overlay with the extension UI. However, it also causes the aggregator UI to "jump" when collapsing and expanding the extension UI.  
To fix this, a simple rule can be applied to the aggregator:

```css
#aggregator {
    transition: right 0.2s ease 0s;
}
```

This matches the transition used by the extension, providing a smooth and seamless motion when users expands/collapses the extension UI.

(Quick note: I'm only using the `!important` rule in the above snippets, because the aggregator currently has its styling applied directly to the element, rather than via a stylesheet. Ideally all the styling would be moved to a stylesheet.)

There are a few other issues as well, but these changes would fix a large part of it and make the script much more usable for users of the extension.

**Comment by RenuzitV** [comment]
This is nice, and since I’m using Better Trade on the left side I hadn’t got bothered enough to make this change. Let me see what can be done about this.
Thanks a lot for the suggestions too!

**Comment by RenuzitV** [comment]
Done.
